export const experiences = [
 {company:'Transamerica',role:'Lead Software Engineer',period:'Apr 2023 — Present',year:'2023',location:'New Jersey',summary:'Leading frontend architecture and secure retirement journeys, from enrollment to withdrawals.',description:'Leading secure retirement and investment journeys across advisor-managed accounts, statements, and TAR-to-PX servicing integration. Contributing to SVS batch modernization with Java and PowerShell, alongside accessible Angular interfaces, API integrations, and production delivery.',tags:['Retirement','Angular','GraphQL','Security','Leadership']},
 {company:'Wells Fargo',role:'Lead Software Engineer',period:'Sep 2022 — Apr 2023',year:'2022',location:'New York',summary:'Built financial-risk workflows with React, Node.js, and real-time processing updates.',description:'Built React and TypeScript features for MOSART financial-risk workflows, including model cycles, workstreams, and Excel/CSV transformations. Integrated Node.js/Express services, Python data services, and live file-upload status through Socket.IO.',tags:['React','Material UI','Node.js','Socket.IO']},
 {company:'Transamerica',role:'Senior Frontend Developer',period:'Mar 2021 — Aug 2022',year:'2021',location:'New Jersey',summary:'Developed Angular self-service experiences for retirement planning, investments, and account management.',description:'Built Participant Experience (PX) journeys for tracking retirement plans, loans, and withdrawals. Used Angular, RxJS, NgRx, and the Cardinal component library to deliver reusable interfaces, secure navigation, reactive forms, and tested self-service workflows.',tags:['Angular','RxJS','NgRx','Testing']},
 {company:'IBM',role:'Angular Developer',period:'Jan 2021 — Mar 2021',year:'2021',location:'Remote',summary:'Created internal HR assessment interfaces with Angular and the IBM Carbon Design System.',description:'Built Angular modules for IBM IQ, an internal HR tool supporting divestiture workflows and employee workload assessments. Used the Carbon Design System, reusable components, REST integrations, and Jasmine/Karma tests.',tags:['Angular','Carbon Design System','Testing']},
 {company:'Paychex',role:'Frontend Developer',period:'Mar 2018 — Dec 2020',year:'2018',location:'Rochester, NY',summary:'Modernized payroll and HR applications, including onboarding, payments, and scheduling.',description:'Built client self-onboarding, real-time payment eligibility, and HR calendar workflows. Modernized AngularJS and Flash applications, added reusable Angular forms and Kendo UI scheduling, and supported AWS delivery and production troubleshooting.',tags:['Payroll','AngularJS','AWS','Jenkins']},
 {company:'Serco (Google)',role:'IT Analyst / Web Developer',period:'Sep 2014 — Dec 2015',year:'2014',location:'Hyderabad, India',summary:'Built internal support tools with AngularJS, Node.js, Express, and MongoDB.',description:'Built and maintained internal feedback and escalation tools for Google support teams using AngularJS, Node.js, Express, and MongoDB. Added authentication, record tracking, and responsive interfaces; resolved cross-browser issues and supported release cycles.',tags:['MEAN stack','Node.js','MongoDB','JWT']}
];
export const projects = [
 {id:'participant-experience',name:'Participant Experience (PX)',client:'Transamerica',category:'Retirement self-service',description:'A unified retirement self-service experience covering account management, enrollment, investments, documents, loans, and withdrawals.',tags:['Angular','RxJS','NgRx','Accessibility'],theme:'mint',focus:['Built reusable interfaces with the Cardinal component library and responsive SCSS styling.','Coordinated dependent data streams with RxJS and centralized application state with NgRx.','Implemented reactive forms, route guards, shared services, and centralized error recovery.','Created Jasmine/Karma tests and supported Jenkins delivery across environments.'],context:'Senior Frontend Developer · March 2021–August 2022. Platform scale: 3.8M participants and approximately $246B in retirement assets, as reported in my latest resume.'},
 {id:'svs-modernization',name:'Stable Value Solutions modernization',client:'Transamerica',category:'Legacy modernization',description:'Modernizing retirement investment batch processes from legacy VBScript to Java 17 and PowerShell, with scheduling, integrations, and deployment support.',tags:['Java 17','PowerShell','Control-M','CI/CD'],theme:'mint',focus:['Worked on converting legacy batch jobs and validating their behavior during the transition.','Supported database integrations and Control-M scheduling for investment operations.','Contributed to on-premises CI/CD, security-scanning onboarding, and application monitoring setup.','Coordinated testing and release preparation across engineering teams.'],context:'March 2025–Present · Goal: improve maintainability and reduce reliance on legacy batch technologies.'},
 {id:'tar-px-mirror',name:'TAR-to-PX Mirror View',client:'Transamerica',category:'Secure retirement servicing',description:'A controlled participant-view experience that lets authorized servicing teams access PX from the participant’s perspective while preserving role-based access.',tags:['SSO','Authorization','Session management','Navigation'],theme:'mint',focus:['Integrated identity management and single sign-on for authorized servicing users.','Worked on role-specific participant-view access and navigation filtering.','Handled session continuity and cross-application navigation between legacy servicing tools and PX.','Contributed to TAR UI optimization and the secure PX jump experience.'],context:'2025–2026 · Goal: connect internal servicing workflows with the modern participant platform.'},
 {id:'release-engineering',name:'Release engineering & platform operations',client:'Transamerica',category:'Production delivery',description:'Release preparation and deployment support for retirement applications, covering CI/CD, database changes, and production readiness.',tags:['CI/CD','Release planning','Monitoring'],theme:'mint',focus:['Supported pipeline configuration and coordinated environment and database changes.','Contributed to testing, production readiness, and release validation.','Worked across application and infrastructure teams to prepare deployments and investigate operational issues.'],context:'Supporting work across retirement-platform releases and modernization initiatives.'},
 {id:'retirement',name:'Creating Participant Experience (PX)',client:'Transamerica',category:'Retirement platform modernization',description:'Building a unified participant-facing experience for retirement account management, enrollment, investments, documents, loans, and withdrawals.',tags:['Angular','RxJS','NgRx','Accessibility'],theme:'mint',focus:['Created reusable interfaces and navigation patterns with the Cardinal component library and responsive SCSS.','Coordinated dependent data streams with RxJS and centralized state with NgRx.','Implemented reactive forms, route guards, shared services, and recovery paths for participant journeys.','Connected REST and GraphQL services while preserving secure access and entitlements.','Supported testing, releases, production validation, and ongoing modernization of retirement experiences.'],context:'Transamerica · Senior Frontend Developer / Lead Software Engineer. PX became the strategic foundation for participant self-service and related servicing integrations.'},
 {id:'risk',name:'MOSART financial-risk workflows',client:'Wells Fargo',category:'Financial risk',description:'React interfaces and Node.js services for financial-risk model cycles, workstreams, and Excel/CSV transformation workflows.',tags:['React','TypeScript','Node.js','Socket.IO'],theme:'peach',focus:['Built reusable Material UI components, Redux state, multi-step validation, and loading/error states.','Developed Excel/CSV upload, validation, and transformation workflows with Node.js and Express.','Integrated Python services and Socket.IO updates to surface real-time processing status.','Worked with architects, QA, model owners, and business teams on delivery tradeoffs and release troubleshooting.'],context:'Lead Software Engineer · September 2022–April 2023.'},
 {id:'payroll',name:'Self Onboarding',category:'Client onboarding',client:'Paychex',description:'A self-service enrollment flow for clients to submit business, banking, pay-schedule, and employee information online.',tags:['Angular','Reactive forms','REST','AWS'],theme:'mint',focus:['Built reusable Angular components and reactive forms for multi-step client enrollment.','Integrated REST services and created responsive Material Design interfaces.','Configured CloudFront and S3 delivery of frontend assets.','Supported transaction analytics, Grafana monitoring, and production fixes.'],context:'March–December 2020 · Frontend Developer.'},
 {id:'paychex-rtp',name:'Real Time Payments',category:'Payroll payments',client:'Paychex',description:'Payment-option workflows enabling eligible employers to pay employees the same day their payroll is processed.',tags:['Payroll','Eligibility workflows','Frontend'],theme:'mint',focus:['Worked on the frontend feature for same-day employee payments.','Supported eligibility workflows covering the client, direct-deposit availability, participating banks, and processing date.'],context:'July 2019–February 2020 · Frontend Developer.'},
 {id:'paychex-calendar',name:'HR Center — Calendar',category:'HR scheduling',client:'Paychex',description:'An employee-events calendar for birthdays, anniversaries, raise dates, and custom events with group invitations.',tags:['Angular','RxJS','Kendo UI','SCSS'],theme:'mint',focus:['Migrated calendar workflows from AngularJS to Angular.','Integrated Kendo UI scheduling and month navigation for past and future events.','Built reusable components and responsive interfaces backed by REST services.','Created unit tests with Jasmine/Karma and supported Selenium-based functional testing.'],context:'October 2018–June 2019 · Frontend Developer.'},
 {id:'paychex-rewrite',name:'Payroll Rewrite',category:'Legacy modernization',client:'Paychex',description:'Replaced a Flash payroll application with web-based screens for entering employee check information.',tags:['AngularJS','JavaScript','REST','Lazy loading'],theme:'mint',focus:['Built payroll interfaces with AngularJS, JavaScript, and responsive styling.','Connected check-information workflows to backend REST services.','Used feature modules and lazy loading to reduce initial loading work.','Created unit tests and supported functional testing of payroll workflows.'],context:'July–September 2018 · Frontend Developer.'},
 {id:'ibm-iq',name:'IBM IQ workload assessment',client:'IBM',category:'Internal HR workflows',description:'Internal tools supporting divestiture workflows and helping managers or delegated assessors complete employee workload assessments.',tags:['Angular','TypeScript','Carbon Design System','REST'],theme:'peach',focus:['Developed Angular modules with reusable Carbon Design System components.','Connected assessment interfaces to REST services and configured navigation between components.','Built responsive SCSS layouts and covered application scenarios with Jasmine/Karma tests.'],context:'Angular Developer · January–March 2021 · Remote.'}

];
export const skills = [{category:'Frontend',items:['Angular','React','TypeScript','JavaScript','React Hooks','Redux','RxJS','NgRx','HTML5','Accessibility']},{category:'Architecture & APIs',items:['REST','GraphQL/Apollo','Microservices/BFF','SAML SSO','Authentication','Authorization','Caching','Feature flags','Drupal CMS']},{category:'Backend & automation',items:['Java','Spring Boot','Node.js','Express.js','PowerShell']},{category:'Cloud & infrastructure',items:['AWS','Terraform','CloudFront','S3']},{category:'Databases & caching',items:['SQL','MySQL','MongoDB','DynamoDB','Redis']},{category:'Quality & delivery',items:['Kiro','GitHub Copilot','AI-assisted development','Jenkins','Git','CI/CD','SonarQube','ESLint','Jasmine/Karma','Selenium','Postman','Kibana','Grafana','Code reviews','Mentoring']},{category:'Design & styling',items:['CSS/SCSS','Material UI','Carbon Design System','Kendo UI','Chart.js','Responsive design']}];

export const education = [
 {degree:'Master of Science in Computer Science',school:'Texas A&M University-Kingsville'},
 {degree:'Bachelor of Technology in Computer Science and Engineering',school:'Jawaharlal Nehru Technological University'}
];

export const recognition = 'Transamerica STAR Award for Outstanding Performance';
