export const experiences = [
 {company:'Transamerica',role:'Lead Software Engineer',period:'Apr 2023 — Present',year:'2023',location:'New Jersey',description:'Leading secure retirement and investment journeys supporting 3.8M participants and approximately $246B in retirement assets. Designing accessible Angular systems, REST/GraphQL integrations, and reliable production workflows.',tags:['Retirement','Angular','GraphQL','Security','Leadership']},
 {company:'Wells Fargo',role:'Lead Software Engineer',period:'Sep 2022 — Apr 2023',year:'2022',location:'New York',description:'Built React and TypeScript features for a data-intensive financial-risk platform, plus Node.js/Express services, Excel/CSV processing, and real-time Socket.IO workflows.',tags:['React','Material UI','Node.js','Socket.IO']},
 {company:'Transamerica',role:'Senior Frontend Developer',period:'Mar 2021 — Aug 2022',year:'2021',location:'New Jersey',description:'Built participant-facing retirement, investment, loan, withdrawal, and self-service workflows with Angular, RxJS, NgRx, reactive forms, route guards, and Jasmine/Karma testing.',tags:['Angular','RxJS','NgRx','Testing']},
 {company:'IBM',role:'Angular Developer',period:'Jan 2021 — Mar 2021',year:'2021',location:'New York',description:'Developed enterprise UI components and contributed to design system documentation.',tags:['Angular','Documentation']},
 {company:'Paychex',role:'Frontend Developer',period:'Mar 2018 — Dec 2020',year:'2018',location:'Rochester, NY',description:'Built payroll, HR, payments, onboarding, calendar, and scheduling applications; modernized AngularJS and Flash workflows and supported AWS, Jenkins, Selenium, Grafana, and production troubleshooting.',tags:['Payroll','AngularJS','AWS','Jenkins']},
 {company:'Serco (Google)',role:'IT Analyst / Web Developer',period:'Sep 2014 — Dec 2015',year:'2014',location:'Hyderabad, India',description:'Developed MEAN-stack internal applications with AngularJS, Node.js, Express, MongoDB, REST services, JWT authentication, and responsive interfaces for Google support teams.',tags:['MEAN stack','Node.js','MongoDB','JWT']}
];
export const projects = [
 {id:'dashboard',name:'Enterprise Dashboard UI',category:'Financial technology',description:'A comprehensive financial dashboard with real-time data visualization, interactive charts, and responsive layouts.',tags:['Angular','D3.js','SCSS','RxJS'],theme:'mint',focus:['Interactive financial data visualization','Responsive dashboard layouts','Reactive user experiences']},
 {id:'design-system',name:'Design System & Component Library',category:'Developer experience',description:'A scalable design system with reusable components, comprehensive documentation, and Storybook integration across enterprise applications.',tags:['React','Storybook','TypeScript','Tailwind'],theme:'peach',focus:['Reusable component architecture','Documented component patterns','Consistent interfaces across applications']}
];
export const skills = [{category:'Frontend',items:['Angular','React','TypeScript','JavaScript','React Hooks','Redux','RxJS','NgRx','HTML5','Accessibility','WCAG']},{category:'Architecture & APIs',items:['REST','GraphQL/Apollo','Node.js','Express.js','Microservices/BFF','SAML SSO','Authentication','Authorization','Caching','Feature flags']},{category:'Cloud & data',items:['Java','Spring Boot','Redis','SQL','MySQL','MongoDB','DynamoDB','AWS','Docker','Kubernetes','OpenShift','Terraform']},{category:'Quality & delivery',items:['GitHub Copilot','AI-assisted development','Prompt engineering','MCP','Jenkins','Git','CI/CD','SonarQube','ESLint','Jasmine/Karma','Selenium','Postman','Kibana','Grafana','Code reviews','Mentoring']},{category:'Design & styling',items:['CSS/SCSS','Material UI','Tailwind','Responsive design','Figma','UI/UX Design']}];

export const education = [
 {degree:'Master of Science in Computer Science',school:'Texas A&M University-Kingsville'},
 {degree:'Bachelor of Technology in Computer Science and Engineering',school:'Jawaharlal Nehru Technological University'}
];

export const recognition = 'Transamerica STAR Award for Outstanding Performance';
