import {useEffect,useRef,useState} from 'react';
type Mode='ready'|'racing'|'crashed';
type S={mode:Mode,lane:number,offset:number,distance:number,score:number,traffic:{lane:number,y:number,color:string}[]};
const palette=['#ff6b8a','#6dd6ff','#ffd166','#c084fc','#fb923c'];
export function Game(){
 const canvas=useRef<HTMLCanvasElement>(null);const state=useRef<S>({mode:'ready',lane:1,offset:0,distance:0,score:0,traffic:[]});const [ui,setUi]=useState({mode:'ready' as Mode,score:0,distance:0});
 useEffect(()=>{const c=canvas.current!,x=c.getContext('2d')!;let raf=0,last=performance.now(),spawn=0;
 const reset=()=>{state.current={mode:'racing',lane:1,offset:0,distance:0,score:0,traffic:[]};setUi({mode:'racing',score:0,distance:0})};
 const car=(cx:number,cy:number,col:string)=>{x.fillStyle=col;x.beginPath();x.roundRect(cx-19,cy-31,38,62,10);x.fill();x.fillStyle='#dff8ff';x.beginPath();x.roundRect(cx-12,cy-21,24,17,5);x.fill();x.fillStyle='#182233';x.fillRect(cx-13,cy+11,26,12);x.fillStyle='#ffec8b';x.fillRect(cx-14,cy-31,8,4);x.fillRect(cx+6,cy-31,8,4)};
 const update=(dt:number)=>{const s=state.current;if(s.mode!=='racing')return;s.offset=(s.offset+dt*.08)%55;s.distance+=dt*.006;s.score=Math.floor(s.distance/10);spawn+=dt;if(spawn>850){spawn=0;s.traffic.push({lane:Math.floor(Math.random()*3),y:-70,color:palette[Math.floor(Math.random()*palette.length)]})}s.traffic.forEach(t=>t.y+=dt*.12);const hit=s.traffic.some(t=>t.lane===s.lane&&t.y>215&&t.y<300);s.traffic=s.traffic.filter(t=>t.y<410);if(hit)s.mode='crashed';setUi({mode:s.mode,score:s.score,distance:Math.floor(s.distance)})};
 const render=()=>{const s=state.current,w=520,h=360,g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#101a35');g.addColorStop(1,'#251340');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='#162d3e';x.fillRect(0,0,120,h);x.fillRect(400,0,120,h);for(let i=0;i<12;i++){x.fillStyle=i%2?'#2de2e6':'#ff4d9d';x.globalAlpha=.45;x.fillRect(30+(i%2)*35,(i*55+s.offset)%h,3,18);x.fillRect(455+(i%2)*35,(i*55+s.offset)%h,3,18)}x.globalAlpha=1;x.fillStyle='#252b46';x.fillRect(120,0,280,h);x.strokeStyle='#6973a8';x.lineWidth=3;x.setLineDash([28,24]);x.lineDashOffset=-s.offset;[213,306].forEach(l=>{x.beginPath();x.moveTo(l,0);x.lineTo(l,h);x.stroke()});x.setLineDash([]);x.strokeStyle='#d7fb79';x.lineWidth=4;x.strokeRect(122,0,276,h);x.fillStyle='#fff';x.font='800 18px system-ui';x.fillText('ROSHAN RUN',22,30);x.font='12px system-ui';x.fillStyle='#b7c6ec';x.fillText('ARROW KEYS / A D',22,50);x.fillText('DIST '+Math.floor(s.distance)+' m',414,28);x.fillText('SCORE '+s.score,414,47);s.traffic.forEach(t=>car(166+t.lane*93,t.y,t.color));car(166+s.lane*93,285,'#d7fb79');if(s.mode!=='racing'){x.fillStyle='rgba(8,12,28,.8)';x.fillRect(0,0,w,h);x.textAlign='center';x.fillStyle='#fff';x.font='800 30px system-ui';x.fillText(s.mode==='ready'?'READY TO RACE':'CRASHED',w/2,135);x.font='14px system-ui';x.fillStyle='#c4d3f7';x.fillText(s.mode==='ready'?'Dodge traffic and chase the high score':'Distance '+Math.floor(s.distance)+' m  •  Score '+s.score,w/2,165);x.fillStyle='#d7fb79';x.font='700 15px system-ui';x.fillText(s.mode==='ready'?'Press Start Race':'Press Restart',w/2,205);x.textAlign='left'}};
 const loop=(now:number)=>{const dt=Math.min(80,now-last);last=now;update(dt);render();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);
 const key=(e:KeyboardEvent)=>{const k=e.key.toLowerCase(),s=state.current;if(k==='enter'&&(s.mode==='ready'||s.mode==='crashed')){reset();return}if(s.mode!=='racing')return;if(k==='arrowleft'||k==='a'){s.lane=Math.max(0,s.lane-1);e.preventDefault()}if(k==='arrowright'||k==='d'){s.lane=Math.min(2,s.lane+1);e.preventDefault()}};window.addEventListener('keydown',key);(window as any).render_game_to_text=()=>JSON.stringify({mode:state.current.mode,lane:state.current.lane,distance:Math.floor(state.current.distance),score:state.current.score,traffic:state.current.traffic.map(t=>({lane:t.lane,y:Math.floor(t.y)})),coordinates:'origin top-left; lanes 0-2'});(window as any).advanceTime=(ms:number)=>{update(ms);render()};return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',key)}},[]);
 const start=()=>window.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter'}));
 return <section className="game-panel"><div className="section-title"><div><span className="eyebrow">A SMALL DETOUR</span><h2>Roshan Run</h2></div><span className="game-score">Score {ui.score}</span></div><p className="game-intro">A neon lane racer. Switch lanes, dodge traffic, and see how far you can drive.</p><canvas ref={canvas} width={520} height={360} aria-label="Roshan Run racing game"/><div className="game-meta"><span>{ui.distance} m</span><span>← → or A D to steer</span></div><button className="outline-button game-start" onClick={start}>{ui.mode==='crashed'?'Restart race':ui.mode==='racing'?'Racing…':'Start race'}</button></section>
}
