import {useEffect,useRef,useState} from 'react';

export function Game(){
 const canvas=useRef<HTMLCanvasElement>(null); const [score,setScore]=useState(0);
 const state=useRef({x:160,y:150,targetX:260,targetY:110,playing:false,score:0});
 useEffect(()=>{const c=canvas.current!,ctx=c.getContext('2d')!; let raf=0;
  const draw=()=>{ctx.fillStyle='#18251d';ctx.fillRect(0,0,520,300);ctx.fillStyle='#c9eb90';ctx.font='700 18px sans-serif';ctx.fillText('ROSHAN RUN',20,30);ctx.font='12px sans-serif';ctx.fillStyle='#a9bb9f';ctx.fillText('Move with arrow keys or WASD • collect the stars',20,52);const s=state.current;ctx.fillStyle='#f4c95d';ctx.beginPath();ctx.arc(s.targetX,s.targetY,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d7fb79';ctx.beginPath();ctx.arc(s.x,s.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#193f32';ctx.font='bold 16px sans-serif';ctx.fillText('r.',s.x-8,s.y+6);ctx.fillStyle='#fff';ctx.font='14px sans-serif';ctx.fillText('Score '+s.score,420,28);raf=requestAnimationFrame(draw)};draw();
  const key=(e:KeyboardEvent)=>{const s=state.current;if(!s.playing)return;const k=e.key.toLowerCase();const d=12;if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k))e.preventDefault();if(k==='arrowup'||k==='w')s.y=Math.max(75,s.y-d);if(k==='arrowdown'||k==='s')s.y=Math.min(280,s.y+d);if(k==='arrowleft'||k==='a')s.x=Math.max(20,s.x-d);if(k==='arrowright'||k==='d')s.x=Math.min(500,s.x+d);if(Math.hypot(s.x-s.targetX,s.y-s.targetY)<28){s.score++;setScore(s.score);s.targetX=35+Math.random()*450;s.targetY=85+Math.random()*190}};window.addEventListener('keydown',key);;(window as any).render_game_to_text=()=>JSON.stringify({mode:state.current.playing?'playing':'ready',player:{x:state.current.x,y:state.current.y},star:{x:state.current.targetX,y:state.current.targetY},score:state.current.score,coordinates:'origin top-left; x right, y down'});;(window as any).advanceTime=()=>draw();return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',key)}} ,[]);
 const start=()=>{state.current.playing=true;setScore(state.current.score)};
 return <section className="game-panel"><div className="section-title"><div><span className="eyebrow">A SMALL DETOUR</span><h2>Roshan Run</h2></div><span className="game-score">Score {score}</span></div><p className="game-intro">Guide the little r. to the glowing star. A tiny arcade break between projects.</p><canvas ref={canvas} width={520} height={300} aria-label="Roshan Run game"/><button className="outline-button game-start" onClick={start}>{state.current.playing?'Playing':'Start game'}</button></section>
}
