import {StrictMode,useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,BriefcaseBusiness,Layers,FolderKanban,Gamepad2,ArrowUpRight,Search,Bookmark,MapPin,ArrowRight,Github,Mail,Check, X, Download} from 'lucide-react';
import {experiences,projects,skills,education,recognition} from './data';
import './theme.css';
import './theme';
import './style.css';

import {Game} from './Game';
import {ResumeDownload} from './ResumeDownload';
type View='Overview'|'Experience'|'Projects'|'Skills'|'Games'|'Saved';
function App(){
 const [view,setView]=useState<View>('Overview'),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[selected,setSelected]=useState<(typeof projects)[number]|null>(null);
 const [saved,setSaved]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem('career-saved')||'[]');return Array.isArray(value)?value.filter((v):v is string=>typeof v==='string'):[]}catch{return []}});
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{try{localStorage.setItem('career-saved',JSON.stringify(saved))}catch{}},[saved]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close()},[selected]);
 const toggle=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const matches=(s:string)=>s.toLowerCase().includes(query.toLowerCase());
 const nav=(v:View)=>{setView(v);setQuery('');setCategory('All');window.scrollTo({top:0,behavior:'instant'})};
 const visibleProjects=projects.filter(p=>matches([p.name,p.description,...p.tags].join(' '))&&(view!=='Saved'||saved.includes(p.id))&&(category==='All'||p.tags.includes(category)));
 return <div className="shell"><a className="skip" href="#main">Skip to content</a><header className="site-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();nav('Overview')}}><span className="brandmark">r.</span><span>by roshan<sup>®</sup></span></a><nav aria-label="Main navigation">{(['Overview','Experience','Projects','Skills','Games','Saved'] as const).map(name=><button key={name} aria-current={view===name?'page':undefined} className={view===name?'active':''} onClick={()=>nav(name)}>{name==='Games'&&<Gamepad2 size={16}/>}<span>{name==='Overview'?'Home':name}</span>{name==='Saved'&&<span className="count">{saved.length}</span>}</button>)}</nav><a className="header-contact" href="mailto:roshanrajani45@gmail.com">Let’s talk <ArrowUpRight size={17}/></a></header><div className="workspace"><main id="main">
{view==='Overview'?<><section className="hero"><div className="hero-topline"><span><span className="dot"/> FRONTEND ENGINEER · NEW JERSEY</span><span>PERSONAL PORTFOLIO / 2026</span></div><div className="hero-grid"><div className="hero-copy"><p className="hello">Hey, I’m Roshan <span>↗</span></p><h1>A little craft.<br/>A lot of<br/><em>possibility.</em></h1><p className="hero-description">I build thoughtful interfaces for complex worlds.<br/>Frontend engineering, with people at the center.</p><div className="hero-actions"><button className="hero-button" onClick={()=>nav('Projects')}>Explore my work <ArrowUpRight size={20}/></button><ResumeDownload/></div><div className="hero-footnote"><span/> CURRENTLY BUILDING AT <strong>Transamerica</strong></div></div><div className="portrait-composition"><div className="portrait-outline"/><figure className="portrait-frame"><img src="/images/roshan.webp" alt="Roshan Rajani outdoors, wearing a beige suit and sunglasses"/><figcaption><span>THE HUMAN BEHIND THE CODE</span><strong>Roshan Rajani</strong></figcaption></figure><span className="portrait-sticker" aria-hidden="true">✳</span><div className="craft-note"><Layers size={20}/><span>Built with intent.<br/><strong>Made to feel simple.</strong></span></div><span className="portrait-coordinate">01 / ENGINEER & EXPERIENCE BUILDER</span></div></div><div className="company-strip"><span>GOOD COMPANY.<br/>MEANINGFUL WORK.</span><div>{['Transamerica','Wells Fargo','IBM','Paychex','Serco'].map(c=><span key={c}>{c}</span>)}</div></div></section><section className="intro-section"><span className="eyebrow">01 / THE APPROACH</span><div><h2>Complex under the hood.<br/><span>Effortless on the surface.</span></h2><p>From retirement journeys to financial platforms, I connect design and engineering to make ambitious ideas work in the real world.</p><div className="principles"><span><Layers size={18}/> Systems that scale</span><span><Check size={18}/> Accessible by design</span><span><ArrowUpRight size={18}/> Details that matter</span></div></div></section></>:<section className={'page-heading '+(view==='Games'?'game-heading':'')}><span className="eyebrow">{view==='Games'?'OFF THE CLOCK / ON THE GRID':'THE ROSHAN COLLECTION'}</span><h1>{{Experience:'Every chapter counts.',Projects:'Ideas, made tangible.',Skills:'A toolkit with purpose.',Games:'A little room to play.',Saved:'The work you kept.'}[view]}</h1><p>{{Experience:'The teams and challenges that shaped how I build.',Projects:'Selected work in financial technology and developer experience.',Skills:'The tools and practices behind the experience.',Games:'Take a detour. Dodge the traffic. Chase your next high score.',Saved:'Your personal shortlist, saved in this browser.'}[view]}</p></section>}
{view==='Games'&&<Game/>}{view!=='Overview'&&view!=='Games'&&<div className="toolbar"><label className="search"><Search size={17}/><input aria-label="Search dashboard" placeholder={`Search ${view.toLowerCase()}…`} value={query} onChange={e=>setQuery(e.target.value)}/></label>{(view==='Projects'||view==='Skills')&&<select aria-label="Filter category" value={category} onChange={e=>setCategory(e.target.value)}>{(view==='Projects'?['All','Angular','React']:['All',...skills.map(s=>s.category)]).map(c=><option key={c}>{c}</option>)}</select>}</div>}
<div className={view==='Overview'?'overview-grid':'detail-grid'}>
{(view==='Overview'||view==='Experience')&&<section className="panel"><div className="section-title"><div><span className="eyebrow">02 / THE JOURNEY</span><h2>Built along the way.</h2></div>{view==='Overview'&&<button className="text-button" onClick={()=>nav('Experience')}>View all <ArrowUpRight size={15}/></button>}</div><div className="timeline">{experiences.filter(e=>matches([e.company,e.role,e.description,...e.tags].join(' '))).slice(0,view==='Overview'?3:6).map((e,i)=><article className="timeline-row" key={e.company+e.period}><div className={'company-icon c'+i}>{e.company[0]}</div><div><div className="row-title"><h3>{e.company}</h3>{e.period.includes('Present')&&<span className="current">Current</span>}</div><p>{e.role}</p><small>{e.period}</small>{view==='Experience'&&<><p className="description">{e.description}</p><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></>}</div></article>)}{!experiences.some(e=>matches([e.company,e.role,e.description,...e.tags].join(' ')))&&<p className="empty">No experience matches your search.</p>}</div></section>}
{(view==='Overview'||view==='Skills')&&<section className="panel skills-panel"><div className="section-title"><div><span className="eyebrow">03 / THE TOOLKIT</span><h2>The right tools.</h2></div><Layers size={20}/></div>{skills.filter(s=>category==='All'||s.category===category).map(s=><div className="skill-group" key={s.category}><span>{s.category}</span><div>{(view==='Overview'?s.items.slice(0,4):s.items).filter(matches).map((skill,i)=><span className="skill-chip" key={skill}><span className={'skill-dot d'+i}/>{skill}</span>)}</div></div>)}{!skills.filter(s=>category==='All'||s.category===category).some(s=>s.items.some(matches))&&<p className="empty">No skills match your search.</p>}<p className="panel-foot">{view==='Overview'?<button className="text-button" onClick={()=>nav('Skills')}>Explore the full toolkit <ArrowUpRight size={16}/></button>:'A toolkit for accessible, scalable interfaces.'}</p>{view==='Skills'&&<><div className="credential-block"><span className="eyebrow">EDUCATION</span>{education.map(e=><p key={e.degree}><strong>{e.degree}</strong><br/><small>{e.school}</small></p>)}</div><div className="credential-block"><span className="eyebrow">RECOGNITION</span><p><strong>{recognition}</strong></p></div></>}</section>}
</div>
{(view==='Overview'||view==='Projects'||view==='Saved')&&<section className="projects-section"><div className="section-title"><div><span className="eyebrow">04 / SELECTED WORK</span><h2>{view==='Saved'?'Saved projects':'From thinking to doing.'}</h2></div>{view==='Overview'&&<button className="text-button" onClick={()=>nav('Projects')}>All projects <ArrowUpRight size={15}/></button>}</div><div className="project-grid">{visibleProjects.map(p=><article className="project" key={p.id}><div className={'project-art '+p.theme} aria-hidden="true"><span className="art-label">{p.id==='dashboard'?'01 / FINANCIAL INTERFACES':'02 / DESIGN SYSTEMS'}</span>{p.id==='dashboard'?<div className="mini-dashboard"><div className="mini-sidebar"/><div className="mini-content"><div className="mini-top">Portfolio overview <span>● LIVE VIEW</span></div><div className="mini-stats"><i/><i/><i/></div><div className="mini-bars">{[35,58,43,74,62,85,72,95].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div></div>:<div className="design-art"><div className="swatches"><i/><i/><i/><i/></div><div className="sample-button">Button <ArrowUpRight size={14}/></div><div className="sample-type">Aa<span>Good systems.<br/>Better experiences.</span></div></div>}</div><div className="project-body"><div className="project-top"><span className="eyebrow">{p.category}</span><button className="icon-button" aria-label={`${saved.includes(p.id)?'Unsave':'Save'} ${p.name}`} aria-pressed={saved.includes(p.id)} onClick={()=>toggle(p.id)}>{saved.includes(p.id)?<Check size={18}/>:<Bookmark size={18}/>}</button></div><button className="project-link" onClick={()=>setSelected(p)}>{p.name}<ArrowUpRight size={20}/></button><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div>{!visibleProjects.length&&<div className="empty"><Bookmark/><h3>{view==='Saved'?'A little space for your favorites.':'No matching projects.'}</h3><p>{view==='Saved'?'Save a project to keep it here on this browser.':'Try another search or filter.'}</p><button className="outline-button" onClick={()=>nav('Projects')}>Browse projects</button></div>}</section>}
{view!=='Games'&&<section className="contact-section"><span className="eyebrow">HAVE SOMETHING IN MIND?</span><a className="contact-headline" href="mailto:roshanrajani45@gmail.com">Let’s make<br/>something <em>matter.</em><ArrowUpRight aria-hidden="true"/></a><div className="contact-bottom"><a href="mailto:roshanrajani45@gmail.com"><Mail size={17}/> roshanrajani45@gmail.com</a><span>GOOD CONVERSATIONS ARE A GREAT START.</span></div></section>}<footer><a className="footer-brand" href="#" onClick={e=>{e.preventDefault();nav('Overview')}}>r.</a><span>© {new Date().getFullYear()} Roshan Rajani</span><span><a href="https://github.com/roshanrajani" target="_blank" rel="noreferrer"><Github size={16}/> GitHub <ArrowUpRight size={15}/></a></span></footer></main></div><dialog aria-label="Project details" ref={dialog} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}><button className="close icon-button" aria-label="Close project details" onClick={()=>setSelected(null)}><X/></button>{selected&&<><span className="eyebrow">{selected.category}</span><h2>{selected.name}</h2><p>{selected.description}</p><h3>Project focus</h3><ul>{selected.focus.map(f=><li key={f}>{f}</li>)}</ul><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><p className="source-note">A summary of Roshan’s portfolio work. Previews are illustrative interface studies; client source code is not included.</p><button className="outline-button" onClick={()=>toggle(selected.id)}>{saved.includes(selected.id)?'Remove from saved':'Save project'}</button></>}</dialog></div>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
