import {StrictMode,useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,BriefcaseBusiness,Layers,FolderKanban,ArrowUpRight,Search,Bookmark,MapPin,ArrowRight,Github,Mail,Check, X, Download} from 'lucide-react';
import {experiences,projects,skills,education,recognition} from './data';
import './style.css';
import './studio.css';
type View='Overview'|'Experience'|'Projects'|'Skills'|'Saved';
function App(){
 const [view,setView]=useState<View>('Overview'),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[selected,setSelected]=useState<(typeof projects)[number]|null>(null);
 const [saved,setSaved]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem('career-saved')||'[]');return Array.isArray(value)?value.filter((v):v is string=>typeof v==='string'):[]}catch{return []}});
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{try{localStorage.setItem('career-saved',JSON.stringify(saved))}catch{}},[saved]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close()},[selected]);
 const toggle=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const matches=(s:string)=>s.toLowerCase().includes(query.toLowerCase());
 const nav=(v:View)=>{setView(v);setQuery('');setCategory('All')};
 const visibleProjects=projects.filter(p=>matches([p.name,p.description,...p.tags].join(' '))&&(view!=='Saved'||saved.includes(p.id))&&(category==='All'||p.tags.includes(category)));
 return <div className="shell"><a className="skip" href="#main">Skip to content</a><aside><a className="brand" href="#" onClick={e=>{e.preventDefault();nav('Overview')}}><span className="brandmark">r.</span><span><span className="light">by </span>roshan<small>DESIGN · CODE · CRAFT</small></span></a><div className="nav-label">WORKSPACE</div><nav>{([['Overview',LayoutDashboard],['Experience',BriefcaseBusiness],['Projects',FolderKanban],['Skills',Layers],['Saved',Bookmark]] as const).map(([name,Icon])=><button key={name} aria-current={view===name?'page':undefined} className={view===name?'active':''} onClick={()=>nav(name)}><Icon size={18}/>{name}{name==='Saved'&&<span className="count">{saved.length}</span>}</button>)}</nav><div className="side-note"><div className="little-icon">↗</div><h3>Let’s build something<br/>that matters.</h3><p>Thoughtful interfaces.<br/>Meaningful experiences.</p><a href="mailto:roshanrajani45@gmail.com">Start a conversation <ArrowUpRight size={16}/></a></div><a className="profile" href="https://roshanrajani.com" target="_blank" rel="noreferrer"><img className="avatar" src="./images/roshan.webp" alt=""/><span><strong>Roshan Rajani</strong><small>Frontend engineer</small></span><ArrowUpRight size={16}/></a></aside><div className="workspace"><header><div><span className="muted">Workspace</span><span className="slash">/</span>{view}</div><div className="header-right"><span className="location"><MapPin size={14}/> New Jersey, US</span><a aria-label="GitHub profile" href="https://github.com/roshanrajani" target="_blank" rel="noreferrer"><Github size={20}/></a><img className="avatar small" src="./images/roshan.webp" alt=""/></div></header><main id="main"><div className="page-heading"><div><div className="eyebrow">ENGINEERING × DESIGN × EXPERIENCE</div><h1>{view==='Overview'?'Beyond the interface.':view==='Saved'?'Your shortlist.':`${view}, in focus.`}</h1><p>{view==='Overview'?'A personal workspace for the work, the craft, and the journey.':'Explore the experience and craft behind the work.'}</p></div><span className="heading-actions"><a className="outline-button" href="/Roshan_Rajani_Frontend.pdf" download><Download size={16}/> Download resume</a><a className="outline-button" href="mailto:roshanrajani45@gmail.com?subject=Hello%20Roshan"><Mail size={16}/> Get in touch <ArrowUpRight size={15}/></a></span></div>
{view==='Overview'&&<><section className="hero studio-hero"><div className="hero-copy"><span className="pill"><span className="dot"/> THE PERSONAL WORKSPACE OF</span><h2>Roshan<br/><em>Rajani<span className="name-period">.</span></em></h2><div className="hero-role">Frontend engineer. <span>Experience builder.</span></div><p>I turn complex systems into interfaces that feel effortless. Enterprise scale. A designer’s eye. A developer’s instinct.</p><div className="hero-actions"><button className="hero-button" onClick={()=>nav('Projects')}>Discover my work <ArrowUpRight size={18}/></button><button className="journey-button" onClick={()=>nav('Experience')}>My journey <ArrowRight size={16}/></button></div><div className="hero-coordinates"><MapPin size={13}/> NEW JERSEY, USA <span>40.7465° N · 74.1563° W</span></div></div><div className="portrait-panel"><img src="./images/roshan.webp" alt="Roshan Rajani wearing a beige suit and sunglasses outdoors"/><div className="portrait-shade"/><span className="photo-index">01 / THE HUMAN</span><div className="portrait-caption"><span>BUILDING WITH PURPOSE</span><strong>Code is the medium.<br/>People are the point.</strong></div><span className="portrait-star" aria-hidden="true">✳</span></div></section><div className="company-strip"><span>CHAPTERS WITH</span><div>Transamerica <i>✦</i> Wells Fargo <i>✦</i> IBM <i>✦</i> Paychex <i>✦</i> Serco</div></div><section className="stats" aria-label="Portfolio summary">{[['06','Career chapters','Across enterprise teams'],['05','Organizations','A cross-industry perspective'],['02','Featured projects','Interfaces & design systems'],['11','Listed skills','From code to craft']].map(([n,l,d])=><div className="stat" key={l}><span>{l}<ArrowUpRight size={15}/></span><strong>{n}</strong><small>{d}</small></div>)}</section></>}
{view!=='Overview'&&<div className="toolbar"><label className="search"><Search size={17}/><input aria-label="Search dashboard" placeholder={`Search ${view.toLowerCase()}…`} value={query} onChange={e=>setQuery(e.target.value)}/></label>{(view==='Projects'||view==='Skills')&&<select aria-label="Filter category" value={category} onChange={e=>setCategory(e.target.value)}>{(view==='Projects'?['All','Angular','React']:['All',...skills.map(s=>s.category)]).map(c=><option key={c}>{c}</option>)}</select>}</div>}
<div className={view==='Overview'?'overview-grid':''}>
{(view==='Overview'||view==='Experience')&&<section className="panel"><div className="section-title"><div><span className="eyebrow">THE JOURNEY</span><h2>Career timeline</h2></div>{view==='Overview'&&<button className="text-button" onClick={()=>nav('Experience')}>View all <ArrowUpRight size={15}/></button>}</div><div className="timeline">{experiences.filter(e=>matches([e.company,e.role,e.description,...e.tags].join(' '))).slice(0,view==='Overview'?3:6).map((e,i)=><article className="timeline-row" key={e.company+e.period}><div className={'company-icon c'+i}>{e.company[0]}</div><div><div className="row-title"><h3>{e.company}</h3>{e.period.includes('Present')&&<span className="current">Current</span>}</div><p>{e.role}</p><small>{e.period}</small>{view==='Experience'&&<><p className="description">{e.description}</p><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></>}</div></article>)}{!experiences.some(e=>matches([e.company,e.role,e.description,...e.tags].join(' ')))&&<p className="empty">No experience matches your search.</p>}</div></section>}
{(view==='Overview'||view==='Skills')&&<section className="panel skills-panel"><div className="section-title"><div><span className="eyebrow">THE TOOLKIT</span><h2>Built with expertise</h2></div><Layers size={20}/></div>{skills.filter(s=>category==='All'||s.category===category).map(s=><div className="skill-group" key={s.category}><span>{s.category}</span><div>{s.items.filter(matches).map((skill,i)=><span className="skill-chip" key={skill}><span className={'skill-dot d'+i}/>{skill}</span>)}</div></div>)}{!skills.filter(s=>category==='All'||s.category===category).some(s=>s.items.some(matches))&&<p className="empty">No skills match your search.</p>}<p className="panel-foot">A toolkit for accessible, scalable interfaces.</p>{view==='Skills'&&<><div className="credential-block"><span className="eyebrow">EDUCATION</span>{education.map(e=><p key={e.degree}><strong>{e.degree}</strong><br/><small>{e.school}</small></p>)}</div><div className="credential-block"><span className="eyebrow">RECOGNITION</span><p><strong>{recognition}</strong></p></div></>}</section>}
</div>
{(view==='Overview'||view==='Projects'||view==='Saved')&&<section className="projects-section"><div className="section-title"><div><span className="eyebrow">SELECTED WORK</span><h2>{view==='Saved'?'Saved projects':'Where craft meets impact'}</h2></div>{view==='Overview'&&<button className="text-button" onClick={()=>nav('Projects')}>All projects <ArrowUpRight size={15}/></button>}</div><div className="project-grid">{visibleProjects.map(p=><article className="project" key={p.id}><div className={'project-art '+p.theme} aria-hidden="true">{p.id==='dashboard'?<div className="mini-dashboard"><div className="mini-sidebar"/><div className="mini-content"><div className="mini-top"/><div className="mini-stats"><i/><i/><i/></div><div className="mini-bars">{[35,58,43,74,62,85,72,95].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div></div>:<div className="design-art"><div className="swatches"><i/><i/><i/><i/></div><div className="sample-button">Button <ArrowUpRight size={14}/></div><div className="sample-type">Aa<span>Design is in the details.</span></div></div>}</div><div className="project-body"><div className="project-top"><span className="eyebrow">{p.category}</span><button className="icon-button" aria-label={`${saved.includes(p.id)?'Unsave':'Save'} ${p.name}`} aria-pressed={saved.includes(p.id)} onClick={()=>toggle(p.id)}>{saved.includes(p.id)?<Check size={18}/>:<Bookmark size={18}/>}</button></div><button className="project-link" onClick={()=>setSelected(p)}>{p.name}<ArrowUpRight size={20}/></button><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div>{!visibleProjects.length&&<div className="empty"><Bookmark/><h3>{view==='Saved'?'A little space for your favorites.':'No matching projects.'}</h3><p>{view==='Saved'?'Save a project to keep it here on this browser.':'Try another search or filter.'}</p><button className="outline-button" onClick={()=>nav('Projects')}>Browse projects</button></div>}</section>}
<footer><span>© {new Date().getFullYear()} Roshan Rajani</span><span>Thoughtfully built with React & TypeScript <span className="dot"/></span></footer></main></div><dialog aria-label="Project details" ref={dialog} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}><button className="close icon-button" aria-label="Close project details" onClick={()=>setSelected(null)}><X/></button>{selected&&<><span className="eyebrow">{selected.category}</span><h2>{selected.name}</h2><p>{selected.description}</p><h3>Project focus</h3><ul>{selected.focus.map(f=><li key={f}>{f}</li>)}</ul><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><p className="source-note">Project summary adapted from Roshan’s existing portfolio. Client source code is not included.</p><button className="outline-button" onClick={()=>toggle(selected.id)}>{saved.includes(selected.id)?'Remove from saved':'Save project'}</button></>}</dialog></div>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
